version: '3.8'
services:
  ## Webserver for Frontend & api ##
  webserver:
    container_name: LibraryServer
    image: webserver
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "4000:80"
      - "4001:443"
    depends_on:
      - database
    volumes:
      - app-data:/var/lib/app-data
    networks:
      server_net:
         ipv4_address: 172.20.0.2 
         
 ## Postgres Database with PGAdmin ## 
  database:
    container_name: PostgresDB
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "4002:5432"
    volumes: 
      - db-data:/var/lib/postgresql/temporary/library
    networks:
        db_net:
            ipv4_address: 172.20.1.2
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "4003:80"
    volumes:
        - db-data:/var/lib/postgresql/temporary/library
    networks:
        db_net:
            ipv4_address: 172.20.1.3
            
volumes:
    db-data:
    app-data:
      
networks:
  server_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
  db_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1
